baseURL = 'https://sonicriders.info/'
languageCode = 'en-us'
title = 'Sonic Riders Database'
"theme" = 'terminal' 
pagination.pagerSize = 7

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

# Table of contents default setup
# Add {{< toc >}} for table of contents
[markup]
  [markup.tableOfContents]
      endLevel = 4
      ordered = true
      startLevel = 2
  [markup.goldmark.renderer]
    # This is so we can embed videos, be careful with this
    #unsafe = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 8

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Sonic Riders Database"

    [languages.en.params]
      subtitle = "My personal portfolio site & the home of Reaper Co. updates"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Sonic Riders Database"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "characters"
          name = "Characters"
          url = "/characters"
        [[languages.en.menu.main]]
          identifier = "gears"
          name = "Gears"
          url = "/gears"
        [[languages.en.menu.main]]
          identifier = "glossary"
          name = "Glossary"
          url = "/glossary"
        [[languages.en.menu.main]]
          identifier = "netplay"
          name = "Netplay"
          url = "/netplay"
        [[languages.en.menu.main]]
          identifier = "tournament rules"
          name = "Tournament rules"
          url = "/tournamentrules"
        [[languages.en.menu.main]]
          identifier = "tournament footage"
          name = "Tournament footage"
          url = "/tournamentfootage"
        [[languages.en.menu.main]]
          identifier = "patch notes"
          name = "Patch Notes"
          url = "/patchnotes"
        